In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import cv2

In [15]:
def LiveCamEdgeDetection_canny(image_color):
    threshold1=30
    threshold2=80
    
    img_gray=cv2.cvtColor(image_color,cv2.COLOR_BGR2GRAY)
    canny=cv2.Canny(img_gray,threshold1,threshold2)
    
    return canny

In [62]:
def LiveCamEdgeDetection_Laplace(image_color):
    
    
    img_gray=cv2.cvtColor(image_color,cv2.COLOR_BGR2GRAY)
    width=img_gray.shape[0]
    Height=img_gray.shape[1]
    
    
    M_rotation=cv2.getRotationMatrix2D((width/2,Height/2),
                                       180,1)
    rotated_image=cv2.warpAffine(img_gray,M_rotation,(width,Height))
    laplace=cv2.Laplacian(rotated_image,cv2.CV_64F)
    return laplace

In [ ]:
def LiveCamEdgeDetection_Sobel(image_color):
    
    img_gray=cv2.cvtColor(image_color,cv2.COLOR_BGR2GRAY)
    x_sobel=cv2.Sobel(img_gray,cv2.CV_64F,1,0,ksize=7)
    y_sobel=cv2.Sobel(img_gray,cv2.CV_64F,0,1,ksize=7)
    
    return x_sobel

In [ ]:
cap=cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()
    cv2.imshow("Live Edge Detection ", LiveCamEdgeDetection_Laplace(frame))
    cv2.imshow("WebCam Video", frame)
    
    if cv2.waitKey(2)==13:
        break
    
cap.release()

cv2.destroyAllWindows()
    
    

True
[[[ 43  40  41]
  [ 43  41  41]
  [ 42  41  40]
  ...
  [ 55  67  79]
  [ 55  66  80]
  [ 54  65  79]]

 [[ 43  41  41]
  [ 42  41  41]
  [ 40  40  39]
  ...
  [ 55  66  79]
  [ 54  65  79]
  [ 53  64  79]]

 [[ 41  40  40]
  [ 40  40  40]
  [ 38  39  39]
  ...
  [ 53  65  79]
  [ 53  64  79]
  [ 53  63  80]]

 ...

 [[185 180 182]
  [182 178 180]
  [177 174 176]
  ...
  [135 139 151]
  [137 139 152]
  [142 143 156]]

 [[183 179 178]
  [182 179 178]
  [180 178 177]
  ...
  [136 139 153]
  [137 139 153]
  [139 140 154]]

 [[181 177 175]
  [184 181 179]
  [183 182 179]
  ...
  [137 139 153]
  [137 139 153]
  [137 138 152]]]
True
[[[ 41  41  48]
  [ 41  41  47]
  [ 40  41  46]
  ...
  [ 53  69  81]
  [ 52  68  81]
  [ 51  67  80]]

 [[ 40  40  46]
  [ 40  40  46]
  [ 39  40  44]
  ...
  [ 52  68  80]
  [ 51  67  80]
  [ 50  66  79]]

 [[ 38  38  44]
  [ 38  39  43]
  [ 38  39  43]
  ...
  [ 50  66  78]
  [ 49  65  78]
  [ 48  64  78]]

 ...

 [[182 179 181]
  [180 177 179]
  [180 177